import {TABLES,emptyState,SCHEMA,uid,log} from '../domain/model.js';
import {validateState} from '../domain/operations.js';
const STORES=[...TABLES,'system','snapshots'];
export function openDatabase(name='oms-pro-v10'){return new Promise((resolve,reject)=>{const request=indexedDB.open(name,SCHEMA);request.onupgradeneeded=()=>{const db=request.result;for(const name of STORES){if(db.objectStoreNames.contains(name))continue;const store=db.createObjectStore(name,{keyPath:'id'});for(const key of ['orderId','supplier','date','paymentId','itemId'])if(!['system','snapshots','audit'].includes(name))store.createIndex(key,key,{unique:false});}};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('برنامه در پنجره دیگری باز است؛ آن را ببندید و دوباره تلاش کنید'));request.onsuccess=()=>{request.result.onversionchange=()=>request.result.close();resolve(request.result);};});}
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
export async function readState(db){const tx=db.transaction([...TABLES,'system'],'readonly');const rows=await Promise.all([...TABLES.map(k=>req(tx.objectStore(k).getAll())),req(tx.objectStore('system').get('meta')),req(tx.objectStore('system').get('settings'))]);const s=emptyState();TABLES.forEach((k,i)=>s[k]=rows[i]);s.meta=rows[TABLES.length]?.value||s.meta;s.settings=rows[TABLES.length+1]?.value||{};return s;}
export async function commit(db,before,next,{migration=null,action=null}={}){
 validateState(next);const after=structuredClone(next);after.meta.revision=(before.meta.revision||0)+1;after.meta.lastSaved=Date.now();if(action)log(after,action,null,{revision:after.meta.revision});
 return new Promise((resolve,reject)=>{const tx=db.transaction(STORES,'readwrite');let failure=null;const sys=tx.objectStore('system'),check=sys.get('meta');check.onsuccess=()=>{try{const current=check.result?.value?.revision||0;if(current!==(before.meta.revision||0))throw Error('اطلاعات در پنجره دیگری تغییر کرده؛ صفحه را تازه‌سازی کنید');if(migration){const id=uid();tx.objectStore('snapshots').put({id,kind:'before-migration',at:Date.now(),state:before});after.meta.rollbackId=id;const sourceId=uid();tx.objectStore('snapshots').put({id:sourceId,kind:'legacy-source',at:Date.now(),raw:migration.raw});after.meta.sourceSnapshotId=sourceId;}
 for(const key of TABLES){const store=tx.objectStore(key),old=new Map(before[key].map(x=>[x.id,x])),ids=new Set(after[key].map(x=>x.id));for(const x of before[key])if(!ids.has(x.id))store.delete(x.id);for(const row of after[key])if(JSON.stringify(old.get(row.id))!==JSON.stringify(row))store.put(row);}
 sys.put({id:'meta',value:after.meta});sys.put({id:'settings',value:after.settings});}catch(e){failure=e;tx.abort();}};tx.oncomplete=()=>resolve(after);tx.onabort=()=>reject(failure||tx.error||Error('ذخیره متوقف شد؛ داده قبلی حفظ شد'));tx.onerror=()=>{failure||=tx.error;};});}
export async function snapshot(db,id){return req(db.transaction('snapshots','readonly').objectStore('snapshots').get(id));}
export async function listSnapshots(db){return req(db.transaction('snapshots','readonly').objectStore('snapshots').getAll());}
export async function rollback(db,current,id){const saved=await snapshot(db,id);if(!saved?.state)throw Error('نسخه قبلی پیدا نشد');const next=structuredClone(saved.state);next.meta.revision=current.meta.revision;next.audit=[...current.audit];return commit(db,current,next,{migration:{raw:null},action:'migration.rollback'});}
