import {SUPPLIERS,today} from './domain/model.js';
export const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=v=>v===null||v===undefined?'نامشخص':new Intl.NumberFormat('fa-IR').format(v);
export const supplier=v=>SUPPLIERS[v]||v;
export function button(text,id,cls=''){return `<button type="button" class="${cls}" data-action="${e(id)}">${e(text)}</button>`;}
export function head(title,sub='',actions=''){return `<div class="page-head"><div><h1>${e(title)}</h1><p>${e(sub)}</p></div><div class="actions">${actions}</div></div>`;}
export function field(name,label,value='',type='text',extra=''){return `<label>${e(label)}<input name="${e(name)}" type="${type}" value="${e(value)}" ${extra}></label>`;}
export function select(name,label,options,value=''){return `<label>${e(label)}<select name="${e(name)}">${options.map(([v,t])=>`<option value="${e(v)}" ${v===value?'selected':''}>${e(t)}</option>`).join('')}</select></label>`;}
export function check(name,label,value=false){return `<label class="check"><input name="${e(name)}" type="checkbox" ${value?'checked':''}>${e(label)}</label>`;}
export const supplierOptions=s=>[...new Set(['ali','vahid',...s.items.map(i=>i.supplier)])].map(x=>[x,supplier(x)]);
export const orderOptions=s=>[['','انتخاب سفارش'],...s.orders.filter(o=>o.date>=s.meta.start&&o.status!=='cancelled').sort((a,b)=>b.date.localeCompare(a.date)).map(o=>[o.id,`${o.date} · ${o.customer} · ${o.code||o.id}`])];
export function modal(title,body,onSubmit,{submit='ذخیره',wide=false,init=null}={}){const d=document.createElement('dialog');d.className=wide?'wide':'';d.innerHTML=`<form><header><h2>${e(title)}</h2><button type="button" data-close aria-label="بستن">×</button></header><div class="form-body">${body}</div><p class="form-error" role="alert"></p><footer><button type="button" data-close>انصراف</button><button class="primary" type="submit">${e(submit)}</button></footer></form>`;document.body.append(d);d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('close',()=>d.remove());d.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const b=d.querySelector('[type=submit]');b.disabled=true;try{await onSubmit(new FormData(ev.target),d);d.close();}catch(err){d.querySelector('.form-error').textContent=err.message;b.disabled=false;}};init?.(d);d.showModal();return d;}
export function notice(text,kind='warning'){return `<div class="notice ${kind}">${e(text)}</div>`;}
export function toast(message,error=false){const t=document.querySelector('#toast');t.textContent=message;t.className=error?'show error':'show';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.className='',5500);}
export function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);return blob.size;}
export function csv(name,rows,columns){const cell=x=>{let t=String(x??'');if(/^[=+\-@\t\r]/.test(t))t="'"+t;return '"'+t.replace(/"/g,'""')+'"';};download(name,'\uFEFF'+[columns.map(x=>cell(x[1])).join(','),...rows.map(r=>columns.map(([k])=>cell(r[k])).join(','))].join('\r\n'),'text/csv;charset=utf-8');}
export function table(el,columns,rows,{actions=null,search=true}={}){let page=0,query='',timer;el.innerHTML=`${search?'<div class="table-toolbar"><input type="search" aria-label="جست‌وجو در جدول" placeholder="جست‌وجو…"><span class="row-count"></span></div>':''}<div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${e(c.label)}</th>`).join('')}${actions?'<th>عملیات</th>':''}</tr></thead><tbody></tbody></table></div><div class="pagination"></div>`;function paint(){const selected=rows.filter(r=>!query||Object.values(r).some(v=>String(v).toLowerCase().includes(query))),count=Math.max(1,Math.ceil(selected.length/40));page=Math.min(page,count-1);el.querySelector('tbody').innerHTML=selected.slice(page*40,page*40+40).map((r,i)=>`<tr>${columns.map(c=>`<td>${c.html?c.html(r):e(c.get?c.get(r):r[c.key])}</td>`).join('')}${actions?`<td class="row-actions">${actions.buttons(r).map((b,j)=>`<button type="button" data-row="${page*40+i}" data-btn="${j}" class="small">${e(b)}</button>`).join('')}</td>`:''}</tr>`).join('')||`<tr><td colspan="${columns.length+1}" class="empty">هنوز رکوردی برای نمایش نیست.</td></tr>`;el.querySelector('.row-count')?.replaceChildren(document.createTextNode(`${money(selected.length)} رکورد`));el.querySelector('.pagination').innerHTML=`<button data-prev ${page===0?'disabled':''}>قبلی</button><span>${money(page+1)} از ${money(count)}</span><button data-next ${page===count-1?'disabled':''}>بعدی</button>`;el.querySelector('[data-prev]').onclick=()=>{page--;paint();};el.querySelector('[data-next]').onclick=()=>{page++;paint();};el.querySelectorAll('[data-row]').forEach(b=>b.onclick=()=>Promise.resolve().then(()=>actions.run(selected[Number(b.dataset.row)],Number(b.dataset.btn))).catch(err=>toast(err.message,true)));}
 el.querySelector('[type=search]')?.addEventListener('input',ev=>{clearTimeout(timer);const val=ev.target.value;timer=setTimeout(()=>{query=val.toLowerCase();page=0;paint();},180);});paint();}
export const amountColumn=(key,label)=>({key,label,get:r=>money(r[key])});
export function bind(root,actions){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>Promise.resolve().then(()=>actions[b.dataset.action]?.()).catch(err=>toast(err.message,true)));}
export function explain(title,values){const labels={gross:'فروش ناخالص',discount:'تخفیف فروشگاه',salesReduction:'کاهش فروش مرجوعی',cost:'بهای خرید خالص',fee:'کارمزد خالص',expenses:'هزینه',received:'دریافت تأییدشده',refundCash:'برگشت وجه پرداخت‌شده',feeWithheld:'کارمزد کسرشده از واریزی اسنپ',opening:'مانده شروع',customerReceipts:'دریافت مشتری',snappReceipts:'واریزی اسنپ‌پی',supplierRefunds:'برگشت وجه تأمین‌کننده',supplierPayments:'پرداخت تأمین‌کننده',refunds:'بازپرداخت مشتری',partnerPayments:'پرداخت سهم همکاری',withdrawals:'برداشت',supplierDue:'بدهی خرید',partnerDue:'سهم همکاری پرداخت‌نشده',unpaidExpenses:'هزینه پرداخت‌نشده',pendingRefunds:'بازپرداخت در انتظار',remainingProfit:'سود شخصی وصول‌شده باقی‌مانده',freeCash:'پول آزاد صندوق'};modal(title,`<p>مبلغ‌ها به تومان هستند. سود نامشخص به معنی صفر بودن سود نیست.</p><dl>${Object.entries(values).map(([k,v])=>`<div><dt>${e(labels[k]||k)}</dt><dd>${money(v)}</dd></div>`).join('')}</dl>`,async()=>{},{submit:'بستن'});}
